<!DOCTYPE html>

<html lang="en-GB">
    <head>
        <title>SLAKCER</title>
        <link rel="stylesheet" href="/css/slacker.css"/>
    </head>
    <body>
        <div class="container">
            <nav>
                <div class="logo">SLACKER</div>
                <div class="menu">
                    <div class="online">
                        <a class="login" href="">Login</a>
                        <a class="register" href="">Register</a>
                    </div>
                    <div class="offline">
                        <p class="username"></p>
                        <a class="logout" href="">Logout</a>
                    </div>
                </div>
            </nav>
            <section class="app-container">
            </section>
        </div>
    </body>
</html>